-- See: https://github.com/mozilla/zamboni/blob/master/apps/constants/base.py
DELETE FROM reviewer_scores
WHERE note_key IN (
  10, -- REVIEWED_ADDON_FULL
  11, -- REVIEWED_ADDON_PRELIM
  12, -- REVIEWED_ADDON_UPDATE
  20, -- REVIEWED_DICT_FULL
  21, -- REVIEWED_DICT_PRELIM
  22, -- REVIEWED_DICT_UPDATE
  30, -- REVIEWED_LP_FULL
  31, -- REVIEWED_LP_PRELIM
  32, -- REVIEWED_LP_UPDATE
  40, -- REVIEWED_PERSONA
  50, -- REVIEWED_SEARCH_FULL
  51, -- REVIEWED_SEARCH_PRELIM
  52, -- REVIEWED_SEARCH_UPDATE
  60, -- REVIEWED_THEME_FULL
  61, -- REVIEWED_THEME_PRELIM
  62, -- REVIEWED_THEME_UPDATE
  80 -- REVIEWED_ADDON_REVIEW
);
